sudo: false
language: bash
services:
- docker
os:
- linux
script:
- make
- "./make/get-simulator-from-appveyor.sh $APPVEYOR_TOKEN `git describe --tags --dirty`"
deploy:
  provider: releases
  api_key:
    secure: GZ0x6DvKDX89P/U7d3OQbvm0ZTU7SjgsY8gLyh6idr60hz+R1qxgo8jn2kGuvKMYdq5OBtNz5fygEM7jjJIxbXGXbD+KFz7ynj8anXKIUi+LINUhIP7vtx0dm8ETKVwi+AUVTyAijlbbzYM0YbuM4na0D2wDPB2Am53R/bOccOJn4H1DEhHHXEX8NmrwP9ke7yikkdnCGG6+E/9R5X7YBt5xEueUd57na3ioM5N20r7f4kIePF/o5OmGcADUYvvig8H55oNZEYtKrnO+/+R6pBAzYCRrIF8dsm2m8QH/fihlryHJexdGtyw1UtvKD8V5d6+gllcR09uSoGZp/eyC25gX/bGP7uruqn/cWOm0l5hRXSb4q+M8zDFJPDvYLYRlTidBfKvwRAO206ExeWFvBzTtvxKvpQozt1nUv04Rg6EKalJNfCQqPryKMdrN4RDa/5z5MuVL5eisrIA9g31q++nj49Kf4SNxxYMaILZQxuYly5uR3SzDOWzONpOn9Pl8nGdF4/qOnxYRI+vD11nPc/bcVwdji/xO0hfWRO+46J9+QVC722+QvgWeeKQ/pwLU9UjuzYvlK1mA5dkcTcN1h4r+LPKs7ADlGX0F6f5Q3qU2qQsh933mcaFFyfxzLleta02vDXk2ge7FdnSQVXSDtzjBAf1/3QUvE0xfZ5PoNP0=
  file:
  - out/factory/bootloader.bin
  - out/factory/partitions.bin
  - out/factory/lamp.bin
  - out/factory/lamp.hex
  - out/simulator/simulator.zip
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: njJX1olFqCc9+2Yg7vtfd0rj7+Kv51EJ/hGghQ4LhEjuZwsmVRqARNTQkOMieNGoKU4jFspGUJt0PgwToruv7coyUSW3dLwTt4rqrCJpyB8jr4I665ubjnAou97JuF/JwesrnE/GgykvC9pCXrMbYP96iwqI7mALV7bX1XrTVzbjBxUoW8CMPSqiyOLAGQjfJJukSqK17A1tTTuamf7AhKwWJdtWxuxgobXFJzcrJ6CrKwsowVb47MVDI1p4KjLU5S7lKE0a841oHWzPoTOr9ALU+XchZRsztAzZMbVbQVpyOX+YU2NbJeyJ4TQ4Tq49tvNypa+Dntoe60g4UaneejVMNBkXo6siatpe6zDvWqm8c8axu1bVi8G72ZC27YHI46tk6K9e+whJkj+S7S8s/y2A7qsF+p+hfJi9rrGbErVMmh29PwnRR7bPXcFzmDfl2iVuXJ9jkTXPiQSsiQq+Bo+QVbrkB6Aa4bbUiS80oCY3V/IJMOJcdlyjNR3d5CE0YhFXs6awA2a0Sw0nwaW0XF+6qw/eMyamB/+/rdn5mndqg8c0185faJEx/bI3LCMeYIegLE2nad1ICSHaRWf08+8QHGWg2lU/rm+OSTHMIpRpFGJfZ67h3sgfqVH/J/aX3ZLRVQmsfhuRrePx3XJBwTbjFju3Yj4Di/aJnXyxSiI=
