version: '{branch}-{build}'
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    $Version = git describe --tags --dirty
    Update-AppveyorBuild -Version $Version
build:
  project: test\simulator\Lamp.sln
  verbosity: minimal
after_build:
- ps: rm test\simulator\Lamp.Simulator\bin\Release\*.pdb
artifacts:
- path: test\simulator\Lamp.Simulator\bin\Release\
  name: simulator