version: '3'
services:
  mcu:
    build:
      context: .
      dockerfile: Dockerfile-mcu
    image: wouterdevinck/lamp-buildenv-mcu
  mcu-basic:
    build:
      context: .
      dockerfile: Dockerfile-mcu-basic
    image: wouterdevinck/lamp-buildenv-mcu-basic
  fpga:
    build:
      context: .
      dockerfile: Dockerfile-fpga
    image: wouterdevinck/lamp-buildenv-fpga
  tool:
    build:
      context: .
      dockerfile: Dockerfile-tool
    image: wouterdevinck/lamp-buildenv-tool