FROM ubuntu:18.10
RUN apt-get update && \ 
    apt-get install -y --no-install-recommends \
      make \
      gcc-avr \
      avr-libc && \
    apt-get autoremove -yqq && \
    apt-get autoclean -yqq && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt