FROM ubuntu:20.04 AS build
COPY install-fpga-tools.sh .
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \ 
    apt-get install -y \
      apt-utils pkg-config \
      git mercurial \
      build-essential clang \
      libffi-dev libftdi-dev \
      graphviz xdot gperf \
      gawk tclsh tcl-dev \
      libreadline-dev bison \
      flex python autoconf \
      libboost-all-dev cmake \
      libeigen3-dev
RUN ./install-fpga-tools.sh
RUN mv /root/fpga/out/bin /root/fpga/out/usr/ && \
    mv /root/fpga/out/lib /root/fpga/out/usr/

FROM ubuntu:20.04
COPY --from=build /root/fpga/out /
ENV DEBIAN_FRONTEND=noninteractive
RUN mkdir -p /root/fpga/out/lib/ && \
    ln -s /lib/ivl /root/fpga/out/lib/ivl && \
    apt-get update && \ 
    apt-get install -y --no-install-recommends \
      make perl tclsh \
      libreadline8 \
      libboost-filesystem1.71.0 \
      libboost-program-options1.71.0 \
      libboost-thread1.71.0 && \
    apt-get autoremove -yqq && \
    apt-get autoclean -yqq && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt